DELETE http://localhost:3001/api/persons/10

###
Get http://localhost:3001/api/persons

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Evelyn",
    "number": "12-43-23435"
}