DELETE http://localhost:3001/api/persons/23
###
Get http://localhost:3001/api/persons/

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Evelyn",
    "number": "213-5894"
}